[pytest]
filterwarnings =
    ignore:.*'soft_unicode' has been renamed to 'soft_str'*:DeprecationWarning
    ignore:unclosed file .*:ResourceWarning
testpaths =
    tests/functional
    tests/unit
markers =
    skip_profile(profile)
    requires_lakekeeper: mark test as requiring a running lakekeeper Iceberg REST catalog
