[pytest]
filterwarnings =
    ignore:.*'soft_unicode' has been renamed to 'soft_str'*:DeprecationWarning
    ignore:unclosed file .*:ResourceWarning
testpaths =
    tests/functional
    tests/unit
markers =
    requires_ducklake
    skip_database_type(database_type)
    skip_profile(profile)
    with_s3_creds
