TEMP_SCHEMA_NAME = "temp_schema_name"
DEFAULT_TEMP_SCHEMA_NAME = "dbt_temp"
DUCKDB_MERGE_LOWEST_VERSION_POSSIBLE = "1.4.0-dev0"
DUCKLAKE_ALTER_RENAME_FIX_VERSION = "1.5.3"
DUCKDB_BASE_INCREMENTAL_STRATEGIES = ["append", "delete+insert"]
